# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22.2'
        cache: true

    - name: Test
      run: go test -v ./...
      
    - name: Setup gf
      run: wget -O gf https://github.com/gogf/gf/releases/latest/download/gf_$(go env GOOS)_$(go env GOARCH) && chmod +x gf && ./gf install -y && rm ./gf
      
    - name: Build
      run: gf build

    - name: Upload Release Assets
      uses: alexellis/upload-assets@0.4.1
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: '["./bin/darwin_amd64/markitdown", "./bin/linux_amd64/markitdown"]'
        asset_content_type: application/octet-stream

    - name: Cleanup
      run: rm -rf bin
